envs:
- MATCH_PASSWORD: ConnectMeCallCenter
- FASTLANE_USER: automation@evernym.com
- FASTLANE_PASSWORD: Evernym@123#
- QA_HOCKEYAPP_TOKEN: 00694d4d102d429593ca7b5cf752473c
- QA_HOCKEYAPP_ID: 1ff7b266f7614d9bb53f279685a6c4d9
- DEV_HOCKEYAPP_ID: 4de29529a5d34f218bf6f3f70900cd6a
- DEV_HOCKEYAPP_TOKEN: fc9455dc95d042d38ddba5784109aee4
- STAGE_HOCKEYAPP_TOKEN: d5ede215aaf34c3dbc80845141a3ad2b
- GITHUB_USER_NAME: iosdev-evernym
- GITHUB_USER_EMAIL: iosdev@evernym.com
- FASTLANE_WORK_DIR: ios
- FASTLANE_LANE: beta
- MAVEN: connectMeUITest
