fastlane_version "2.27.0"

default_platform :android
platform :android do
  before_all do
     ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
end

lane :alpha do
  path = '../app/build.gradle'
  reVersionCode = /versionCode\s+(\d+)/
  reVersionName = /versionName\s+(\S+)/
  androidBuildGradleFileContent = File.read(path)
  versionCode = (androidBuildGradleFileContent[reVersionCode, 1].to_i+1)
  androidBuildGradleFileContent[reVersionCode, 1] = versionCode.to_s
  versionName = androidBuildGradleFileContent[reVersionName, 1]
  versionName = versionName.gsub!(/\A"|"\Z/, '')
  nameArray = versionName.split('.')
  versionNameMinorNumber = nameArray.pop().to_i+1
  versionName = nameArray.join('.')
  androidBuildGradleFileContent[reVersionName, 1] = "\"" + versionName.to_s + "." + versionNameMinorNumber.to_s + "\""
  androidBuildGradleFile = File.new(path, 'w')
  androidBuildGradleFile.write(androidBuildGradleFileContent)
  androidBuildGradleFile.close
  gradle(
    task: "assemble",
    build_type: "Release",
  )

  ENV["BUILD_VERSION_CODE"] = versionCode.to_s
  remote_branch = git_branch
  remote_branch = remote_branch.split('/').last

  if remote_branch == "master"
    ENV["BUILD_NAME"] = "QA ConnectMe"
    hockey(api_token: ENV["HOCKEY_APP_API_TOKEN"], bypass_cdn: true)
  elsif remote_branch == "stable" || remote_branch == "stage"
    ENV["BUILD_NAME"] = "Stable ConnectMe"
    hockey(api_token: ENV["HOCKEY_APP_STAGE_ANDROID_API_TOKEN"], bypass_cdn: true)
  else
    ENV["BUILD_NAME"] = "Dev ConnectMe"
    puts "Current working directory is: " + Dir.pwd
    hockey(api_token: ENV["HOCKEY_APP_DEV_API_TOKEN"], bypass_cdn: true, apk: "app/build/outputs/apk/release/app-armeabi-v7a-release.apk")
    hockey(api_token: ENV["HOCKEY_APP_DEV_API_TOKEN"], bypass_cdn: true, apk: "app/build/outputs/apk/release/app-arm64-v8a-release.apk")
    hockey(api_token: ENV["HOCKEY_APP_DEV_API_TOKEN"], bypass_cdn: true, apk: "app/build/outputs/apk/release/app-x86-release.apk")
    hockey(api_token: ENV["HOCKEY_APP_DEV_API_TOKEN"], bypass_cdn: true, apk: "app/build/outputs/apk/release/app-x86_64-release.apk")
  end

end

  after_all do |lane|
     slack(channel: "connectme_build", message: "#{ENV["BUILD_NAME"]} Android build #{ENV["BUILD_VERSION_CODE"]}")
  end

  error do |lane, exception|
     slack(
       message: exception.message,
       success: false
     )
  end
end
